version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Senai@132"
      ACCEPT_EULA: "Y"

  api:
        image: api
        container_name: api-teste   
        ports:
            - "5000:80"
        depends_on:
            - sql-server-db